apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: action-controller
  template:
    metadata:
      labels:
        name: action-controller
    spec:
      serviceAccountName: action-controller
      containers:
        - name: action-controller
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - action-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "action-controller"
